import Head from "next/head";
import { allocineReacteurApi } from "@/utils/apis";

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Hollywood Boulevard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export const getServerSideProps = async () => {
  let dataToSend = [];
  try {
    const { data } = await allocineReacteurApi.get("/top_rated");
    console.log("data", data);
  } catch (error) {
    console.log(error.message);
  }
  return {
    props: {
      data: dataToSend,
    },
  };
};
